  class OpenStackRubySDK::Heat::GeneralApiInformation < Peace::Model
    		# GET /
		# POST /v1/​{tenant_id}​/stacks
		# POST /v1/​{tenant_id}​/stacks
		# GET /v1/​{tenant_id}​/stacks
		# POST /v1/​{tenant_id}​/stacks/preview
		# PUT /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/preview
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/resources
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​
		# PUT /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​
		# DELETE /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​
		# DELETE /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/abandon
		# POST /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/snapshots
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/snapshots
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/snapshots/​{snapshot_id}​
		# DELETE /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/snapshots/​{snapshot_id}​
		# POST /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/snapshots/​{snapshot_id}​/restore
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/outputs
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/outputs/​{output_key}​
		# POST /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/actions
		# POST /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/actions
		# POST /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/actions
		# POST /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/actions
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/resources
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/resources/​{resource_name}​
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/resources/​{resource_name}​/metadata
		# POST /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/resources/​{resource_name}​/signal
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/events
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/events
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/resources/​{resource_name}​/events
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/resources/​{resource_name}​/events/​{event_id}​
		# GET /v1/​{tenant_id}​/stacks/​{stack_name}​/​{stack_id}​/template
		# GET /v1/​{tenant_id}​/template_versions
		# POST /v1/​{tenant_id}​/validate
		# GET /v1/​{tenant_id}​/resource_types/​{type_name}​/template
		# GET /v1/​{tenant_id}​/resource_types/​{type_name}​
		# GET /v1/​{tenant_id}​/resource_types
		# GET /v1/​{tenant_id}​/build_info
		# POST /v1/​{tenant_id}​/software_configs
		# GET /v1/​{tenant_id}​/software_configs/​{config_id}​
		# DELETE /v1/​{tenant_id}​/software_configs/​{config_id}​
		# GET /v1/​{tenant_id}​/software_deployments
		# POST /v1/​{tenant_id}​/software_deployments
		# GET /v1/​{tenant_id}​/software_deployments/metadata/​{server_id}​
		# GET /v1/​{tenant_id}​/software_deployments/​{deployment_id}​
		# PUT /v1/​{tenant_id}​/software_deployments/​{deployment_id}​
		# DELETE /v1/​{tenant_id}​/software_deployments/​{deployment_id}​
		# GET /v1/​{tenant_id}​/services

  end
