  class OpenStackRubySDK::Glance::ImageTag < Peace::Model
    		# GET /
		# GET /v2/images
		# POST /v2/images
		# GET /v2/images/​{image_id}​
		# PATCH /v2/images/​{image_id}​
		# DELETE /v2/images/​{image_id}​
		# POST /v2/images/​{image_id}​/actions/reactivate
		# POST /v2/images/​{image_id}​/actions/deactivate
		# PUT /v2/images/​{image_id}​/file
		# GET /v2/images/​{image_id}​/file
		# PUT /v2/images/​{image_id}​/tags/​{tag}​
		# DELETE /v2/images/​{image_id}​/tags/​{tag}​
		# GET /v2/images/​{image_id}​/members
		# POST /v2/images/​{image_id}​/members
		# GET /v2/images/​{image_id}​/members/​{member_id}​
		# PUT /v2/images/​{image_id}​/members/​{member_id}​
		# DELETE /v2/images/​{image_id}​/members/​{member_id}​
		# GET /v2/schemas/images
		# GET /v2/schemas/image
		# GET /v2/schemas/members
		# GET /v2/schemas/member
		# GET /v2/metadefs/resource_types
		# POST /v2/metadefs/namespaces/​{namespace_id}​/resource_types
		# GET /v2/metadefs/namespaces/​{namespace_id}​/resource_types
		# DELETE /v2/metadefs/namespaces/​{namespace_id}​/resource_types/​{name}​
		# POST /v2/metadefs/namespaces
		# GET /v2/metadefs/namespaces
		# GET /v2/metadefs/namespaces/​{namespace_id}​
		# PUT /v2/metadefs/namespaces/​{namespace_id}​
		# DELETE /v2/metadefs/namespaces/​{namespace_id}​
		# POST /v2/metadefs/namespaces/​{namespace_id}​/properties
		# GET /v2/metadefs/namespaces/​{namespace_id}​/properties
		# GET /v2/metadefs/namespaces/​{namespace_id}​/properties/​{property_name}​
		# PUT /v2/metadefs/namespaces/​{namespace_id}​/properties/​{property_name}​
		# DELETE /v2/metadefs/namespaces/​{namespace_id}​/properties/​{property_name}​
		# POST /v2/metadefs/namespaces/​{namespace_id}​/objects
		# GET /v2/metadefs/namespaces/​{namespace_id}​/objects
		# GET /v2/metadefs/namespaces/​{namespace_id}​/objects/​{object_name}​
		# PUT /v2/metadefs/namespaces/​{namespace_id}​/objects/​{object_name}​
		# DELETE /v2/metadefs/namespaces/​{namespace_id}​/objects/​{object_name}​
		# POST /v2/metadefs/namespaces/tags/​{namespace_id}​
		# GET /v2/metadefs/namespaces/tags/​{namespace_id}​
		# DELETE /v2/metadefs/namespaces/tags/​{namespace_id}​
		# POST /v2/metadefs/namespaces/tags/​{namespace_id}​/​{tag_name}​
		# GET /v2/metadefs/namespaces/tags/​{namespace_id}​/​{tag_name}​
		# PUT /v2/metadefs/namespaces/tags/​{namespace_id}​/​{tag_name}​
		# DELETE /v2/metadefs/namespaces/tags/​{namespace_id}​/​{tag_name}​
		# GET /v2/schemas/metadefs/namespace
		# GET /v2/schemas/metadefs/namespaces
		# GET /v2/schemas/metadefs/object
		# GET /v2/schemas/metadefs/objects
		# GET /v2/schemas/metadefs/property
		# GET /v2/schemas/metadefs/properties
		# GET /v2/schemas/metadefs/tag
		# GET /v2/schemas/metadefs/tags
		# GET /v2/schemas/metadefs/resource_type
		# GET /v2/schemas/metadefs/resource_types
		# POST /v2/tasks
		# GET /v2/tasks
		# GET /v2/tasks/​{task_id}​

  end
